theme: jekyll-theme-minimal

# 你的求职方向，比如前端开发工程师等
title: NBA球员/小前锋/大前锋/控卫

# 对你自己的简洁描述
description: 小皇帝篮球智商极高、突破犀利，拥有出色的视野和传球技术，被认为是NBA有史以来最为全能的球员之一

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: 勒布朗·詹姆斯(LeBron Raymone James)

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: LeBron@unkown.com

# 你目前的住址
address: 美国洛杉矶

# 你毕业院校
school: 圣文森特·圣玛丽高中

# 你的专业
profession: 专业篮球运动员

# 你的学位
degree: 高中没毕业

# 你获得过的证书或奖励
credential: 三届MVP/三届NBA冠军/三届奥运会冠军
